### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by George20730** [sundevista/local-quotes#27]
Great plugin some issues.

1. both the Documentation and Roadmap option give me a 404 error :( 
 I did end up getting my documentation from https://sundevista.github.io/local-quotes/

2. in the documentation I found at https://sundevista.github.io/local-quotes/terms/search/ that i can do "search *" but the * option does not work, is there a way to just get a random quote no matter the author?

Thanks for the great plugin

**Comment by sundevista** [comment]
@George20730 Hi! I checked links in readme.md and will update them right now. Talking about the searching issue, it'd be nice if you could send me a sample of the problematic quote-block and output of statistics modal (you can find it by searching for "local quotes stat" in your command palette). It can help me understand what is wrong.

**Comment by George20730** [comment]
OK now i feel stupid :) 

As it now works perfect

I tried the code from the documentation

```localquote
id DHsh
search *
refresh 1d
```
And i ended up with the message

You've tried to find an author that doesn't exist

— undefined

But now it works fine :) i don't know why but it works so i can't complain :) 

I will start adding real quotes now and then put the code block in my dailynote 


Thanks for you quick response

**Comment by sundevista** [comment]
@George20730 Maybe something was caught while copying, but I'm glad all is okay now. By the way, if you want to use quotes in your daily notes, you may be interested in [one-time quotes](https://sundevista.github.io/local-quotes/block-types/one-time-quote-block/). As for now, I'm closing the issue, but you can create one more if something wrong with the plugin.
